### ISSUE TITLE
Can handel handle ;-) what this cloudformation template does?  If not, what features need to be added?

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel#64]
https://github.com/byu-oit-appdev/aws-accounts-to-cmdb/blob/newawesomer/cf.yml

**Comment by dsw88** [comment]
Haha loved the pun! The only thing from this template that's not supported in Handel yet is CloudWatch Events. The good news is that CloudWatch Events is also how scheduled Lambda executions work, so this one should come for free as a result of doing the scheduled lambdas work. It looks like a small service to implement; I can probably get it done on Monday.

**Comment by pauldeden** [comment]
Great news!  Thanks.

**Comment by dsw88** [comment]
@pauldeden The functionality to create a CloudWatch Events rule based on an event like Organizations should be in place now. See https://github.com/byu-oit-appdev/handel/wiki/CloudWatch-Events for the docs on the new service. It includes an example showing a CloudWatch Events service invoking a Lambda on certain event types. 

I wasn't able to test this one fully since the account I was in didn't have CloudTrail enabled, which is what CloudWatch Events uses for these event patterns. The rule did create though, and looked like it would fire correctly.

**Comment by pauldeden** [comment]
Thanks!
