### ISSUE TITLE
Separate parameter store parameter name sections with . instead of -?

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel#69]
Currently, parameter names sections are separated with dashes, as done [here](https://github.com/byu-oit-appdev/dsw88-testapp/blob/master/app.js).

In Crazy Friday, we decided on an <appname>.<env>.<variable name> convention for Systems Manager Parameter Store parameter names.

Periods also seem to coincide with the convention showed at http://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-paramstore-access.html

What do you think?

**Comment by dsw88** [comment]
I'll change the parameter names to support periods instead of dashes. Moving this issue to the Handel roadmap project.

**Comment by dsw88** [comment]
PR #77 is changing parameter store access to grant access to the entire application's namespace (all services defined in the Handel file), rather than limiting it to just the service being run. This change will fix this issue because it allows the entire application namespace, which includes specifying the section separations with periods.

**Comment by pauldeden** [comment]
+1
