### ISSUE TITLE
SNS & Beanstalk - Allow Beanstalk to consume events from SNS

### ISSUE THREAD

**Issue by GaryGSC** [byu-oit-appdev/handel#74]
Create and then confirm(?) SNS subscriptions.

**Comment by dsw88** [comment]
I'd like to talk to you about your use case so I can make sure I understand what you're trying to do, but I think this is already implemented and available through your Beanstalk having a service dependency on the SNS topic instead of a service event.

SNS won't send events to Beanstalk the service itself, but it can send to the HTTP endpoint in the Beanstalk app. When you consume SNS as a service dependency in Beanstalk, you'll have permissions to subscribe to the topic, as well as post to it. 

There may still be value in making Beanstalk an event "consumer" for SNS and just setting up an HTTP subscription for you if people want to do it in that way. Let's talk a bit and see what we come up with.

**Comment by GaryGSC** [comment]
At the time, I didn't realize listing an SNS topic as a beanstalk dependency gave the appropriate permissions to subscribe at will.

I think I interpreted dependencies as things the resource was allowed to access (essentially, outbound traffic) and event_consumers as things that would automatically get some sort of notification, since that's how those properties work with Lambdas.

I don't really see a need for this request anymore.
