### ISSUE TITLE
Does handel clear out old source code zip files in its s3 bucket?

### ISSUE THREAD

**Issue by pauldeden** [byu-oit-appdev/handel#86]
Just checking to make sure we aren't paying for storing zip files (cheap as they are) we don't need anymore.

If we aren't yet deleting old zip files, one method could be setting a lifecycle rule on the bucket that deletes files older than a certain number of days.

**Comment by dsw88** [comment]
We're not deleting old zip files in S3 yet. I've got a task on the roadmap to implement a cleanup of some sort. I hadn't thought about an S3 bucket lifecycle rule, that's the easiest way to implement cleanup, although it comes at some cost of flexibility in cleanup policies.

**Comment by dsw88** [comment]
This issue is on the roadmap to address the lack of cleanup: https://github.com/byu-oit-appdev/handel/issues/49

**Comment by dsw88** [comment]
Turns out we can't really use lifecycle rules, because if a deploy doesn't happen for longer than 30 days, then all the artifacts including the currently deployed one will be deleted. 

Instead, I'm going to add some code to clean up everything older than 30 days during a deploy. We'll also always keep the most recent 5 versions, even if they are older than 30 days, just in case.

**Comment by dsw88** [comment]
This should be implemented now.
